version: '3'
services:
  my_rest:
    build: .
    environment:
      - CONSUL_ADDR=127.0.0.1
    ports:
      - "8080:8080"
    volumes:
      - /audio:/audio
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - /audio:/usr/share/nginx/html
    links:
      - my_rest
